<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<title>中羽在线 优质羽毛球互动门户</title>
<meta http-equiv="x-ua-compatible" content="ie=7" />
<meta name="description" content="中羽在线网(BadmintonCN.com)是国内第一羽毛球互动门户，羽毛球网站，包括羽毛球球迷论坛，羽毛球教学视频，羽毛球比赛规则，比赛视频，新闻资讯，技术讨论，球星资料，羽毛球器材装备库，羽毛球俱乐部，球友博客等栏目，拥有专业丰富的羽毛球资讯和火爆的球迷互动社区。" />
<meta name="keywords" content="羽毛球,羽毛球论坛,羽毛球网站,羽毛球教学视频,羽毛球比赛规则,羽毛球装备器材,羽毛球APP,badminton" />
<meta name="robots" content="follow,index" />
<link href="cbo_news/style/dedecms.css" rel="stylesheet" media="screen" type="text/css" />
<link href="cbo_news/style/style.css" rel="stylesheet" media="screen" type="text/css" />
</head>
<body>
<div class="container">
<div class="menu-hot"></div>
<div class="topmenu">
<div class="topinfo" id="topinfo">载入信息中...</div>
<div><a href="//www.badmintoncn.com">首页</a><a href="javascript:window.external.AddFavorite('//www.badmintoncn.com','中羽在线 第一羽毛球互动门户-中国羽球在线')">添加收藏</a><a href="" onClick="this.style.behavior='url(#default#homepage)';this.setHomePage('//www.badmintoncn.com');">设为首页</a><a href="//bbs.badmintoncn.com/thread-340183-1-1.html" target="_blank" style="color:#fff100;">中羽APP</a></div>
</div>
<div class="top">
<div class="logo"><a href="./"><img src="cbo_news/style/img/logo.png" alt="中国羽球在线" /></a></div>
<div class="so">
<form name="formsearch" action="search.php">
<input name="keyword" id="keyword" type="text" style="color:#999;" size="20" value="输入要找的内容..." onfocus="if(this.value=='输入要找的内容...'){this.value='';}" />
<input type="submit" value="SERACH" class="button2" onclick="subs();">
</form>
</div>
</div>
<div class="menu">
<div class="Nav">
<table cellpadding="0" cellspacing="0" border="0">
<tr align="center">
<td>
<b><a href="/list-13.html">羽坛动态</a></b> <a href="/list-1.html">新闻</a> <a href="/list-2.html">赛事</a> <a href="/list-3.html">人物</a> <a href="/list-4.html">官方</a><br />
<b><a href="/list-15.html">品牌资讯</a></b> <a href="/list-16.html">动向</a> <a href="/list-17.html">新品</a> <a href="/list-18.html">评测</a> <a href="/list-19.html">活动</a></td>
<td>
<b><a href="/list-14.html">羽球课堂</a></b> <a href="/list-6.html">基础</a> <a href="/list-7.html">技术</a> <a href="/list-8.html">战术</a> <br />
<b><a href="/cbo_eq" target="_blank" style="color:#ffcc00;">装&nbsp; 备&nbsp;库</a></b> <a href="/cbo_eq/brandlist.php" target="_blank">品牌</a> <a href="/cbo_eq/list.php" target="_blank">产品</a> <a href="/cbo_eq/commlist.php" target="_blank">点评</a></td>
<td>
<b><a href="//club.badmintoncn.com" target="_blank" style="color:#7ecef4;">俱&nbsp; 乐&nbsp;部</a></b><br />
<b><a href="//bbs.badmintoncn.com/home.php" target="_blank" style="color:#00ff00;">球友空间</a></b></td>
<td>
<b><a href="//bbs.badmintoncn.com" target="_blank" style="color:#ff0000;">球迷社区</a></b>&nbsp;&nbsp;<a href="//bbs.badmintoncn.com/forum-81-1.html" target="_blank">赛事</a> <a href="//bbs.badmintoncn.com/forum-18-1.html" target="_blank">技术</a> <a href="//bbs.badmintoncn.com/forum-19-1.html" target="_blank">器材</a><br />
<b><a href="//bbs.badmintoncn.com/thread-340183-1-1.html" target="_blank">中羽APP</a></b>&nbsp;&nbsp;<a href="//bbs.badmintoncn.com/forum-17-1.html" target="_blank">资源</a> <a href="//bbs.badmintoncn.com/forum-35-1.html" target="_blank">优惠</a> <a href="//bbs.badmintoncn.com/forum-64-1.html" target="_blank">二手</a></td>
<td>
<b><a href="/cbo_gym">羽毛球馆</a></b><br />
<b><a href="/cbo_star">球星资料</a></b></td>
<td>
<a href="/cbo_tec" target="_blank">找教练</a><br />
<a href="//bbs.badmintoncn.com/forum-12-1.html" target="_blank">找球友</a></td>
<td>
<a href="//bbs.badmintoncn.com/forum-62-1.html" target="_blank">宣传</a><br />
<a href="/cbo_shop" target="_blank">商店</a>
<td class="bgn">
<a href="/e/" target="_blank">测评室</a><br />
<a href="/s/" target="_blank">活动区</a></td>
</td>
</tr>
</table>
</div>
</div>
<div class="main">
<div id="cboas_85" style="margin-bottom:5px;"><cboa id="cboa_85"></div><div class="spacer"></div>
<div class="box">
<div class="left-box">
<div class="index-pic">
<div class="slideshow" id="slideshow">
<div class="image">
<ul>
<li>
<a href="view-21426-1.html" target="_blank">
<img src="/uploads/image/2018/20181029093539_XoL6s.jpg" width="320" height="240" alt="">
</a>
<div class="caption">一黑到底！国羽男双新锐首夺世界巡回赛冠军</div>
</li>
<li>
<a href="view-21425-1.html" target="_blank">
<img src="/uploads/image/2018/20181029093338_1TjUa.jpg" width="320" height="240" alt="">
</a>
<div class="caption">不失一局！“雅思组合”摘得法国公开赛冠军</div>
</li>
<li>
<a href="view-21424-1.html" target="_blank">
<img src="/uploads/image/2018/20181029093142_5mUfZ.jpg" width="320" height="240" alt="">
</a>
<div class="caption">国羽反弹法国赛收3冠 谌龙横扫石宇奇称王</div>
</li>
<li>
<a href="view-21311-1.html" target="_blank">
<img src="/uploads/image/2018/20180924092610_Br71y.jpg" width="320" height="240" alt="">
</a>
<div class="caption">国羽仅获1冠 陈雨菲丢12分惨遭马林横扫</div>
</li>
<li>
<a href="view-21306-1.html" target="_blank">
<img src="/uploads/image/2018/20180922171357_Cfm8s.jpg" width="320" height="240" alt="">
</a>
<div class="caption">官方确认李宗伟罹患早期鼻癌 恢复良好</div>
</li>
</ul>
</div>
<ul class="trigger" id="trigger">
<li onclick="slideshow.pos(0)">1</li>
<li onclick="slideshow.pos(1)">2</li>
<li onclick="slideshow.pos(2)">3</li>
<li onclick="slideshow.pos(3)">4</li>
<li onclick="slideshow.pos(4)">5</li>
</ul>
<script src="cbo_news/style/tinyslider.js"></script>
<script>
var slideshow=new TINY.slider.slide('slideshow',{
id:'slideshow',
auto:4,
resume:false,
vertical:false,
navid:'trigger',
activeclass:'current',
position:0,
rewind:false,
elastic:true
});
</script>
</div>
</div>
<div class="left-box-1">
<div class="title-2"><span><a href="/cbo_star/" target="_blank">球星资料</a><a href="/cbo_star/star_allOrder.php" target="_blank">人气排名</a></span>人物报道</div>

<div class="list-2">
<div class="list-2-top"><div class="list-2-pic"><a href="view-21310-1.html" target="_blank"><img src="/uploads/image/2018/20180923095744_VJJiN.png" width="100" height="75" alt="李宗伟患癌发声:一切请关注官方声明 感谢球迷关心"></a></div>
<a href="view-21310-1.html" target="_blank">李宗伟患癌发声:感谢球迷关心</a>北京时间9月22日，针对大马一哥李宗伟的病情，马来西亚羽毛球协会发表官方申明，确…</div>
<div class="list-2-top"><div class="list-2-pic"><a href="view-20783-1.html" target="_blank"><img src="/uploads/image/2018/20180527111149_mQiuc.jpg" width="100" height="75" alt="不卖惨! 李雪芮:职业生涯最差1场 我技不如人"></a></div>
<a href="view-20783-1.html" target="_blank">不卖惨! 李雪芮:职业生涯最差1场</a>2018年尤伯杯羽毛球赛对中国女单来说是一场噩梦，三场单打全部失利，总比分2-3…</div>
<div id="cboas_89"><cboa id="cboa_89" style="margin-bottom:10px;"></div><div class="spacer"></div>
<a href="view-21550-1.html" target="_blank">林丹：2018非常不理想 未来再难也要拼东京奥运</a><br />
<a href="view-21548-1.html" target="_blank">揭秘戴资颖六大独门绝技 每招都让对手招架不住</a><br />
<a href="view-21547-1.html" target="_blank">小黄人组合本赛季名副其“10” 决赛胜率史上罕见</a><br />
<a href="view-21546-1.html" target="_blank">李宗伟寄语吴堇眨翰灰满足现状世青赛仅是开始</a><br />
<a href="view-21544-1.html" target="_blank">江湖已不是以前的江湖 李雪芮复出之路并不好走</a><br />
<a href="view-21540-1.html" target="_blank">从常胜将军到威猛不再 羽球天王林丹正悄然改变</a><br />
<a href="view-21533-1.html" target="_blank">郑思维/黄雅琼入选浙江青春领袖 敢闯敢拼勇奋斗</a><br />
<a href="view-21532-1.html" target="_blank">2018桃田PK六大高手18胜4负 谁能压制一哥成难题</a><br />
</div>
</div>
</div>
<div class="center-box">
<div class="title-1"><span><a href="/list-13.html">更多新闻</a></span>羽坛动态</div>
<div class="list-1">
<div class="list-1-top"><a href="view-21426-1.html" class="hot" target="_blank">一黑到底！国羽男双新锐首夺世界巡回赛冠军</a>拿下最后一分后，周昊东激动地躺在赛场上，韩呈恺奔向场边与教练拥抱。这对国羽男双新锐组合28日在法国公开赛决赛中... <a href="view-21426-1.html" target="_blank">[详细]</a></div>
<div class="list-1-top"><a href="view-21425-1.html" class="hot" target="_blank">不失一局！“雅思组合”摘得法国公开赛冠军</a>中国队选手郑思维/黄雅琼28日在法国羽毛球公开赛混双决赛中以21：19、21：14战胜韩国组合徐承宰/蔡侑玎，... <a href="view-21425-1.html" target="_blank">[详细]</a></div>
<div class="list-1-top"><a href="view-21424-1.html" class="hot" target="_blank">国羽反弹法国赛收3冠 谌龙横扫石宇奇称王</a>北京时间10月29日消息，2018年世界羽联世界巡回赛法国公开赛落下帷幕，中国队赢得三项冠军成为最大赢家。谌龙... <a href="view-21424-1.html" target="_blank">[详细]</a></div>
<ul>
<li><span>23日</span>・ <a href="view-21550-1.html" target="_blank" title="林丹：2018非常不理想 未来再难也要拼东京奥运">林丹：2018非常不理想 未来再难也要拼东京奥运</a></li>
<li><span>23日</span>・ <a href="view-21549-1.html" target="_blank" title="国羽仅剩混双排第一 女双远逊日本 男女单有进步">国羽仅剩混双排第一 女双远逊日本 男女单有进步</a></li>
<li><span>22日</span>・ <a href="view-21548-1.html" target="_blank" title="揭秘戴资颖六大独门绝技 每招都让对手招架不住">揭秘戴资颖六大独门绝技 每招都让对手招架不住</a></li>
<li><span>22日</span>・ <a href="view-21547-1.html" target="_blank" title="小黄人组合本赛季名副其“10” 决赛胜率史上罕见">小黄人组合本赛季名副其“10” 决赛胜率史上罕见</a></li>
<li><span>22日</span>・ <a href="view-21546-1.html" target="_blank" title="李宗伟寄语吴堇眨翰灰满足现状世青赛仅是开始">李宗伟寄语吴堇眨翰灰满足现状世青赛仅是开始</a></li>
<div class="list-1-top"></div>
<li><span>22日</span>・ <a href="view-21545-1.html" target="_blank" title="整个赛季胜率九成 桃田戴资颖均只输掉六场比赛">整个赛季胜率九成 桃田戴资颖均只输掉六场比赛</a></li>
<li><span>22日</span>・ <a href="view-21544-1.html" target="_blank" title="江湖已不是以前的江湖 李雪芮复出之路并不好走">江湖已不是以前的江湖 李雪芮复出之路并不好走</a></li>
<li><span>22日</span>・ <a href="view-21543-1.html" target="_blank" title="《法新社》撰文分析林丹 从“超级丹到林一轮”">《法新社》撰文分析林丹 从“超级丹到林一轮”</a></li>
<li><span>22日</span>・ <a href="view-21542-1.html" target="_blank" title="羽联排名:桃田雄霸天下 林李第13第14" 同命相怜"">羽联排名:桃田雄霸天下 林李第13第14"同命相怜"</a></li>
<li><span>22日</span>・ <a href="view-21541-1.html" target="_blank" title="印度国际赛李雪芮完胜进次轮 男单三将险胜晋级">印度国际赛李雪芮完胜进次轮 男单三将险胜晋级</a></li>
<div class="list-1-top"></div>
<li><span>21日</span>・ <a href="view-21540-1.html" target="_blank" title="从常胜将军到威猛不再 羽球天王林丹正悄然改变">从常胜将军到威猛不再 羽球天王林丹正悄然改变</a></li>
<li><span>21日</span>・ <a href="view-21539-1.html" target="_blank" title="羽联首度回应国羽男双疑似打假球 称调查公开透明">羽联首度回应国羽男双疑似打假球 称调查公开透明</a></li>
<li><span>21日</span>・ <a href="view-21538-1.html" target="_blank" title="2018羽毛球世青赛单项夺冠 四位新冠军自评成长">2018羽毛球世青赛单项夺冠 四位新冠军自评成长</a></li>
<li><span>20日</span>・ <a href="view-21537-1.html" target="_blank" title="2018年小戴马林双姝统治 国羽1冠复兴仍路漫漫">2018年小戴马林双姝统治 国羽1冠复兴仍路漫漫</a></li>
<li><span>20日</span>・ <a href="view-21536-1.html" target="_blank" title="2018印尼男双9金比" 雅思"还强 PK国羽两强档5连杀">2018印尼男双9金比"雅思"还强 PK国羽两强档5</a></li>
<div class="list-1-top"></div>
<li>・ <a class="class" href="list.php?id=21542" target="_blank">[官方]</a> <a href="view-21542-1.html" target="_blank">2018年11月22日国际羽联最新排名</a></li>
<li>・ <a class="class" href="list.php?id=21473" target="_blank">[官方]</a> <a href="view-21473-1.html" target="_blank">2018年11月08日国际羽联最新排名</a></li>
<li>・ <a class="class" href="list.php?id=21434" target="_blank">[官方]</a> <a href="view-21434-1.html" target="_blank">2018年11月01日国际羽联最新排名</a></li>
</ul>
</div>
<div class="list-1-bot list_top_compart"><a style="color:green" href="//bbs.badmintoncn.com/forum-62-1.html" target="_blank"><b>培训/招商/推广</b></a> <a style="COLOR: #ff00ff" href="//bbs.badmintoncn.com/forum-64-1.html" target=_blank><b>二手交易</b></a> <a style="color: blue" href="//bbs.badmintoncn.com/forum-35-1.html" target="_blank">商家优惠 快去淘宝贝</a> <a style="color:red" href="//bbs.badmintoncn.com/thread-340183-1-1.html" target="_blank"><b>中羽在线APP</b></a></div>
</div>
<div class="right-box">
<div id="cboas_88" style="margin-bottom:1px;"><cboa id="cboa_88"></div>
<div class="title-3"><span><a href="/view-20405-1.html" target="_blank">2018年国际赛程</a></span><a href="/s" target="_blank" title="更多">近期专题/活动</a></div>
<div class="list-3-1">
<ul>
<li><img src="/uploads/image/2018/20180912161732_gWDfM.jpg" width="70" height="50" /><a href="view-21258-1.html" style="color:" target="_blank">【活动】观《败者为王》赢YONEX秋季好礼 天斧99球拍</a></li>
<li><img src="/uploads/image/2018/20180727180647_pqAk7.jpg" width="70" height="50" /><a href="view-20942-1.html" style="color:" target="_blank">【活动】记录世锦赛精彩瞬间 赢取YONEX天斧88战拍！</a></li>
<li><img src="/uploads/image/2018/20180726133551_RHVg9.jpg" width="70" height="50" /><a href="view-20934-1.html" style="color:" target="_blank">【竞猜】中国李宁，羽你更合拍-世锦赛竞猜赢谌龙同款球拍！</a></li>
<li><img src="http://www.badmintoncn.com/cbo_img/gg/20180608102423ltw2fj8aVz.jpg" width="70" height="50" /><a href="view-20829-1.html" style="color:" target="_blank">【限量】李宗伟亲临现场，球迷见面会限量门票等你拿！</a></li>
<li><img src="/uploads/image/2018/20180514173609_JGPvv.jpg" width="70" height="50" /><a href="view-20650-1.html" style="color:" target="_blank">【竞猜】中国李宁，羽你更合拍-汤尤杯竞猜赢国羽同款球拍</a></li>
<li><img src="/uploads/image/2018/20180514173303_Oa4ky.png" width="70" height="50" /><a href="view-20649-1.html" style="color:" target="_blank">【征集】快来参加赞斯特ZAMST超薄护腕征集测评活动</a></li>
<li><img src="/uploads/image/2018/20180223173942_lEe2M.jpg" width="70" height="50" /><a href="view-20393-1.html" style="color:" target="_blank">中羽在线2018新春跟帖送祝福抢金币赢神秘大奖活动</a></li>
</ul>
<div class="list-3-1-bot"><a href="/about/contact.html" target="_blank">活动合作联系</a> </div>
</div> </div>
<div class="spacer"></div>
</div><div style="margin-bottom:7px;">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2789652892036370" data-ad-slot="4060668446" data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<div class="box">
<div class="left-box">
<div class="title-2"><span><a href="/list-18.html">查看更多</a></span>装备评测室</div>
<div class="list-2">
<div class="list-2-top"><div class="list-2-pic"><a href="view-21279-1.html" target="_blank"><img src="/uploads/image/2018/20180918121611_ZcnDn.jpg" width="100" height="75" alt="人人能打却不是人人能杀的拍子―Yonex AstroX 99评测体验"></a></div>
<a href="view-21279-1.html" target="_blank">Yonex AstroX 99评测体验</a>在一个狂风暴雨雷电交加的夜晚，这支AX99送到了我的手里。&#160;&#160…</div>
<div class="list-2-top"><div class="list-2-pic"><a href="view-21235-1.html" target="_blank"><img src="/uploads/image/2018/20180831181030_9JgnB.jpg" width="100" height="75" alt="在成长为高手的路上，你或许会想要一支duora8xp"></a></div>
<a href="view-21235-1.html" target="_blank">YONEX duora8xp测评</a>&#160;Duora8xp注定不是一支热门的球拍。在酒吧中若你点上一杯DryM…</div>
<a href="view-21279-1.html" target="_blank">人人能打却不是人人能杀的拍子―Yonex Astro</a><br />
<a href="view-21235-1.html" target="_blank">在成长为高手的路上，你或许会想要一支duora8xp</a><br />
<a href="view-21234-1.html" target="_blank">强化进攻的能量75(N9II)――李宁能量75C球拍</a><br />
<a href="view-21233-1.html" target="_blank">Namd新势力-YONEX AstroX88s/d球</a><br />
<a href="view-20725-1.html" target="_blank">每项运动都应得一双好球鞋: 李宁锋影Pro评测</a><br />
</div>
</div>
<div class="center-box">
<div class="title-1"><span><a href="/list-15.html">更多资讯</a></span>品牌资讯</div>
<div class="list-1">
<div class="list-1-top"><a href="view-20662-1.html" class="hot" style="color:red;" target="_blank">YONEX惊喜礼袋伴你开启春季运动潮</a>4月21日起，凡在尤尼克斯授权店铺买满1588元即有机会获得惊喜礼袋礼袋内包含：王者之志纪念写真集一本/羽毛球... <a href="view-20662-1.html" target="_blank">[详细]</a></div>
<a class="class" href="list.php?id=20662" target="_blank">[活动]</a> <a href="view-20662-1.html" target="_blank">YONEX惊喜礼袋伴你开启春季运动潮</a><br />
<a class="class" href="list.php?id=20631" target="_blank">[动向]</a> <a href="view-20631-1.html" target="_blank">强强联手 2018道达尔&#8226;李宁李</a><br />
<a class="class" href="list.php?id=20566" target="_blank">[动向]</a> <a href="view-20566-1.html" target="_blank">2018年首都高校李宁五羽轮比羽毛球赛圆满落幕</a><br />
<a class="class" href="list.php?id=20558" target="_blank">[动向]</a> <a href="view-20558-1.html" target="_blank">2018首都高校李宁五羽轮比羽毛球赛圆满结束</a><br />
<a class="class" href="list.php?id=20348" target="_blank">[活动]</a> <a href="view-20348-1.html" target="_blank">大咖降临！徐晨现身李宁羽球冬令营传“冠军意志”</a><br />
<a class="class" href="list.php?id=20187" target="_blank">[活动]</a> <a href="view-20187-1.html" target="_blank">2017道达尔&#8226;李宁李永波杯3v3</a><br />
<a class="class" href="list.php?id=19998" target="_blank">[动向]</a> <a href="view-19998-1.html" target="_blank">悠闲出游在金秋 YONEX秋季大回馈</a><br />
<a class="class" href="list.php?id=19979" target="_blank">[动向]</a> <a href="view-19979-1.html" target="_blank">YONEX全新系列产品ASTROX「天斧77」</a><br />
<a class="class" href="list.php?id=19821" target="_blank">[动向]</a> <a href="view-19821-1.html" target="_blank">动感与激情 威健・澳加林2017-2018新款</a><br />
<a class="class" href="list.php?id=19807" target="_blank">[动向]</a> <a href="view-19807-1.html" target="_blank">鲍春来现身李宁羽毛球夏令营 向营员传授“冠军</a><br />
</div>
</div>
<div class="right-box">
<div class="title-3"><span><a href="/cbo_eq" target="_blank">更多装备</a></span>装备器材库</div>
<div class="list-3-2">
<ul>
<li><a href="/cbo_eq/view_1987.html" target="_blank"><img src="/cbo_eq/upload/200905/s_20090514101302BokV4LLpSg.jpg" width="50" height="50" title="A-03点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">A-03</span></a></li>
<li><a href="/cbo_eq/view_776.html" target="_blank"><img src="/cbo_eq/upload/200808/s_200808061732321Gyjt4bRgq.jpg" width="50" height="50" title="Super Ti 4200点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">Super</span></a></li>
<li><a href="/cbo_eq/view_3158.html" target="_blank"><img src="/cbo_eq/upload/201007/s_20100728104310yXCSZ9FqU2.gif" width="50" height="50" title="377点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">377</span></a></li>
<li><a href="/cbo_eq/view_239.html" target="_blank"><img src="/cbo_eq/upload/200807/s_20080716104506xl2gVXp1fk.jpg" width="50" height="50" title="TACTIC 穿线机点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">TACTI</span></a></li>
<li><a href="/cbo_eq/view_4697.html" target="_blank"><img src="/cbo_eq/upload/201108/s_20110829213342OJFlBoHcnc.jpg" width="50" height="50" title="KAWASAKE_B-65点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">KAWAS</span></a></li>
<li><a href="/cbo_eq/view_1721.html" target="_blank"><img src="/cbo_eq/upload/200901/s_20090102124128OC37uS6Kt8.jpg" width="50" height="50" title="YY-CLUB 特惠级点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">YY-CL</span></a></li>
<li><a href="/cbo_eq/view_1963.html" target="_blank"><img src="/cbo_eq/upload/200905/s_20090513161333R3jxWrty6h.jpg" width="50" height="50" title="ALB-671点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">ALB-6</span></a></li>
<li><a href="/cbo_eq/view_842.html" target="_blank"><img src="/cbo_eq/upload/200808/s_20080810231102cmr3A3896k.jpg" width="50" height="50" title="射手座点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">射手座</span></a></li>
<li><a href="/cbo_eq/view_1127.html" target="_blank"><img src="/cbo_eq/upload/200808/s_20080828180510fnvw19WONt.jpg" width="50" height="50" title="P-7383点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">P-738</span></a></li>
<li><a href="/cbo_eq/view_4288.html" target="_blank"><img src="/cbo_eq/upload/201104/s_20110426220555AumEYud4vi.jpg" width="50" height="50" title="MAO-9点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">MAO-9</span></a></li>
<li><a href="/cbo_eq/view_6341.html" target="_blank"><img src="/cbo_eq/upload/201508/s_2015081015565452L7nc66Cm.jpg" width="50" height="50" title="铭剑SABER 2013点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">铭剑SAB</span></a></li>
<li><a href="/cbo_eq/view_2329.html" target="_blank"><img src="/cbo_eq/upload/200908/s_20090820125620eHff4t2Klm.jpg" width="50" height="50" title="POWERSHOT NANO1100点评：条
评星：星" style="border:1px solid #ccc" /><br /><span style="font-size:11px;">POWER</span></a></li>
</ul>
</div>
</div>
<div class="spacer"></div>
</div>
<div class="bbs-title"></div>
<div class="bbs-box">
<div class="bbs-box-1">
<a href="//bbs.badmintoncn.com/forum-81-1.html" target="_blank">赛事球星</a><br />
<a href="//bbs.badmintoncn.com/forum-28-1.html" target="_blank">大话羽球</a><br />
<a href="//bbs.badmintoncn.com/forum-18-1.html" target="_blank">技术交流</a><br />
<a href="//bbs.badmintoncn.com/forum-33-1.html" target="_blank">运动保健</a><br />
<a href="//bbs.badmintoncn.com/forum-19-1.html" target="_blank">神兵利器</a><br />
<a href="//bbs.badmintoncn.com/forum-82-1.html" target="_blank">装备鉴定</a><br />
<a href="//bbs.badmintoncn.com/forum-17-1.html" target="_blank">视频资源</a><br />
<a href="//bbs.badmintoncn.com/forum-64-1.html" target="_blank">跳蚤市场</a><br />
<a href="//bbs.badmintoncn.com/forum-35-1.html" target="_blank">商家优惠</a><br />
<a href="//bbs.badmintoncn.com/forum-62-1.html" target="_blank">培训推广</a><br />
<a href="//bbs.badmintoncn.com/forum-65-1.html" target="_blank">交易咨询</a><br />
</div>
<div class="bbs-box-3">
<div class="index-text-box">
<div class="title-3" style="margin-bottom:10px;">最新精华</div>
<script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=51"></script>
<div class="list_top_compart">
<a href="//bbs.badmintoncn.com/forum-35-1.html" target="_blank" style="color:#FF3399;"> 商家优惠 快去淘宝贝</a><br />
<a href="//bbs.badmintoncn.com/thread-340183-1-1.html" target="_blank" style="color:green;">中羽在线手机APP正式发布</a>
</div>
</div>
</div>
<div class="bbs-box-2">
<div class="index-hot"><script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=456"></script></div>
<div id="index-froum">
<a href="#" class="now" onMouseMove="selectContent('tagContent0',this);return false;">24小时热帖</a>
<a href="#" onMouseMove="selectContent('tagContent1',this);return false;">最新话题</a>
<a href="#" onMouseMove="selectContent('tagContent2',this);return false;">最新回复</a>
<a href="#" onMouseMove="selectContent('tagContent3',this);return false;">一周热门</a>
</div>
<div class="index-text">
<div id="tagContent0">
<script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=45"></script>
</div>
<div id="tagContent1" style="display:none;">
<script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=42"></script>
</div>
<div id="tagContent2" style="display:none;">
<script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=49"></script>
</div>
<div id="tagContent3" style="display:none;">
<script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=50"></script>
</div>
</div>
</div>
<div class="bbs-box-4">
<ul><script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=60"></script>
<div class="spacer"></div>
</ul>
</div>
<div class="spacer"></div>
</div>
<script type="text/javascript">

function selectContent(showContent,obj){
var tag = document.getElementById("index-froum").getElementsByTagName("a");
var taglength = tag.length;
for(i=0; i<taglength; i++){
tag[i].className = "a";
}
obj.className = "now";

for(j=0; j<4;j++){
document.getElementById("tagContent"+j).style.display = "none";

}
document.getElementById(showContent).style.display = "block";

}
</script>
<div id="cboas_86" style="margin-bottom:7px;"><cboa id="cboa_86"></div><div class="spacer"></div>
<div class="box">
<div class="left-box">
<div class="title-3"><span><a href="/cbo_user/user.php?in=gym&amp;action=add" target="_blank">登记</a></span><a href="/cbo_gym/index.php" target="_blank">球馆库</a></div>
<div class="list-1-1">
<div class="list-2-top">
<div class="list-2-pic"><a href="/cbo_gym/gym_1648.html" target="_blank" title="查看『北京丽泽桥金星羽羽毛球馆』的详细情况"><img src="/cbo_gym/upload/201103/s_20110301140357PFrGjQCfoF.jpg" width="100" height="66" alt="北京丽泽桥金星羽羽毛球馆" vspace="5" /></a></div>
<a href="/cbo_gym/gym_1648.html" target="_blank" title="查看『北京丽泽桥金星羽羽毛球馆』的详细情况">北京丽泽桥金星羽羽毛</a>场地：木地板铺塑胶<br />地区：北京市 - 丰台区<br />设施：<strong>4</strong> / 消费：<strong>4</strong> / 服务：<strong>5</strong>
</div>
<a href="#" class="class">湘潭市</a> | <a href="/cbo_gym/gym_2533.html" target="_blank" title="查看『湘潭市雨湖区湘潭大学花溪羽毛球馆』的详细情况">湘潭市雨湖区湘潭大学花溪羽毛球馆</a><br />
<a href="#" class="class">合肥市</a> | <a href="/cbo_gym/gym_2532.html" target="_blank" title="查看『庐阳区神马健身运动中心』的详细情况">庐阳区神马健身运动中心</a><br />
<a href="#" class="class">顺义区</a> | <a href="/cbo_gym/gym_2531.html" target="_blank" title="查看『北京启航酒店羽毛球馆』的详细情况">北京启航酒店羽毛球馆</a><br />
<a href="#" class="class">西城区</a> | <a href="/cbo_gym/gym_2530.html" target="_blank" title="查看『北京月坛体育馆』的详细情况">北京月坛体育馆</a><br />
<a href="#" class="class">南宁市</a> | <a href="/cbo_gym/gym_2526.html" target="_blank" title="查看『百灵鸟G1体育馆』的详细情况">百灵鸟G1体育馆</a><br />
<a href="#" class="class">南京市</a> | <a href="/cbo_gym/gym_2524.html" target="_blank" title="查看『南京宏淮羽毛球馆』的详细情况">南京宏淮羽毛球馆</a><br />
</div>
</div>
<div class="center-box">
<div class="title-3"><span><a href="/forum.php?mod=post&amp;action=newthread&amp;fid=62" target="_blank">发布</a></span><a href="/forum.php?mod=forumdisplay&amp;fid=62" target="_blank">培训/招商/推广</a></div>
<div class="list-1-1">
<script type="text/javascript" src="//bbs.badmintoncn.com/api.php?mod=js&amp;bid=202"></script>
</div>
</div>
<div class="right-box">
<div class="title-3"><span><a href="/cbo_user/user.php?in=tec&amp;action=add" target="_blank">登记</a></span><a href="/cbo_tec/index.php" target="_blank">教练库</a></div>
<div class="list-1-1">
<a href="#" class="class">湘潭市</a> | <a href="/cbo_tec/tec_2333.html" target="_blank">湘潭市湘潭大学花溪羽</a><br />
<a href="#" class="class">深圳市</a> | <a href="/cbo_tec/tec_2332.html" target="_blank">“热羽”青少年羽毛球</a><br />
<a href="#" class="class">其它</a> | <a href="/cbo_tec/tec_2331.html" target="_blank">重庆羽毛球教练 专业</a><br />
<a href="#" class="class">深圳市</a> | <a href="/cbo_tec/tec_2330.html" target="_blank">南山马家龙专业少儿成</a><br />
<a href="#" class="class">合肥市</a> | <a href="/cbo_tec/tec_2329.html" target="_blank">合肥驭风羽毛球培训</a><br />
<a href="#" class="class">普陀区</a> | <a href="/cbo_tec/tec_2328.html" target="_blank">上海专业各区羽毛球教</a><br />
<a href="#" class="class">福州市</a> | <a href="/cbo_tec/tec_2327.html" target="_blank">丁媛</a><br />
<a href="#" class="class">杨浦区</a> | <a href="/cbo_tec/tec_2325.html" target="_blank">上海杨浦地区羽毛球私</a><br />
<a href="#" class="class">徐汇区</a> | <a href="/cbo_tec/tec_2324.html" target="_blank">上海专业羽毛球培训羽</a><br />
<a href="#" class="class">广州市</a> | <a href="/cbo_tec/tec_2323.html" target="_blank">广州（越秀、荔湾）专</a><br />
</div>
</div>
<div class="spacer"></div>
</div>
<div class="box">
<div class="left-box">
<div class="title-3"><span><a href="/cbo_user/user.php?in=bbsad&amp;action=Buy&amp;aid=38" target="_blank">购买自助广告位</a></span>广告展示</div>
<div class="list-1-1"><div id="cboas_38" style="margin-top:10px;"><cboa id="cboa_38"></div></div>
</div>
<div class="center-box">
<div class="title-3"><a href="/cbo_star/index.php" target="_blank">一周人气球星</a></div>
<div class="list-1-1">
<ul>
<li><a href="/cbo_star/star_173.html" target="_blank"><img src="/cbo_star/upstar/173.jpg" width="55" height="55px" title="本周人气指数：432点
本月人气指数：2268点
年度人气指数：19467点
总体人气指数：2037616点" /><br />李宗伟</a></li>
<li><a href="/cbo_star/star_315.html" target="_blank"><img src="/cbo_star/upstar/315.jpg" width="55" height="55px" title="本周人气指数：378点
本月人气指数：1674点
年度人气指数：16353点
总体人气指数：539210点" /><br />陈仁杰</a></li>
<li><a href="/cbo_star/star_570.html" target="_blank"><img src="/cbo_star/upstar/570.jpg" width="55" height="55px" title="本周人气指数：369点
本月人气指数：1503点
年度人气指数：15093点
总体人气指数：21672点" /><br />吴柳萤</a></li>
<li><a href="/cbo_star/star_560.html" target="_blank"><img src="/cbo_star/upstar/560.jpg" width="55" height="55px" title="本周人气指数：369点
本月人气指数：1575点
年度人气指数：15804点
总体人气指数：40725点" /><br />拉特查诺・</a></li>
<li><a href="/cbo_star/star_1232.html" target="_blank"><img src="/cbo_star/upstar/1232.jpg" width="55" height="55px" title="本周人气指数：351点
本月人气指数：1557点
年度人气指数：15300点
总体人气指数：29628点" /><br />陈虹蓉</a></li>
<li><a href="/cbo_star/star_567.html" target="_blank"><img src="/cbo_star/upstar/567.jpg" width="55" height="55px" title="本周人气指数：342点
本月人气指数：1395点
年度人气指数：20124点
总体人气指数：61182点" /><br />栗原文音</a></li>
<li><a href="/cbo_star/star_679.html" target="_blank"><img src="/cbo_star/upstar/679.jpg" width="55" height="55px" title="本周人气指数：333点
本月人气指数：1368点
年度人气指数：16848点
总体人气指数：29628点" /><br />奥原希望</a></li>
<li><a href="/cbo_star/star_1394.html" target="_blank"><img src="/cbo_star/upstar/1394.jpg" width="55" height="55px" title="本周人气指数：189点
本月人气指数：927点
年度人气指数：8487点
总体人气指数：47682点" /><br />韩呈恺</a></li>
<li><a href="/cbo_star/star_1062.html" target="_blank"><img src="/cbo_star/upstar/1062.jpg" width="55" height="55px" title="本周人气指数：171点
本月人气指数：990点
年度人气指数：19359点
总体人气指数：40428点" /><br />乔斌</a></li>
<li><a href="/cbo_star/star_556.html" target="_blank"><img src="/cbo_star/upstar/556.jpg" width="55" height="55px" title="本周人气指数：162点
本月人气指数：630点
年度人气指数：5787点
总体人气指数：11890点" /><br />黄宇翔</a></li>
</ul>
<div class="spacer"></div>
<span class="class">hsy0825</span>对<a href="/cbo_star/star_677.html" target="_blank" class="class">大堀彩</a>说：<span title="加油，超级喜欢你">加油，超级喜欢你...</span><br />
<span class="class">yaomadei</span>对<a href="/cbo_star/star_173.html" target="_blank" class="class">李宗伟</a>说：<span title="兄弟啊~~  你原来在这里  还以为受关注的全是美女… 还是你长的秀气~~">兄弟啊~~ 你原来在这里 ...</span><br />
<span class="class">老老马</span>对<a href="/cbo_star/star_1138.html" target="_blank" class="class">何冰娇</a>说：<span title="你和陈雨菲都一样，没有像林丹那种狠劲和狼性，抗压力太差，不会打顶风球，陈雨菲的体能很多时候都不能支撑她第三局，身体太瘦了，体能储备太少了，另外，对方吼你？你也可以吼对方啊，本来你的技术不会比马琳差多少，如果当天你发挥好了就能赢她的，掉分了就要更努力跑并观察对方的弱点在那里？多动脑筋去想怎么才能打死对方，要有耐性。也许这不是你的错，性格造成的，希望国羽今后能挑选一些有更多血性，抗压能力更强的球员出来打国际比赛吧。">你和陈雨菲都一样，没有像林丹...</span><br />
<span class="class">swarding99</span>对<a href="/cbo_star/star_494.html" target="_blank" class="class">张之博</a>说：<span title="张导，您在沈阳哪里教球 有微信号吗？">张导，您在沈阳哪里教球 有微...</span><br />
<span class="class">hujian257</span>对<a href="/cbo_star/star_46.html" target="_blank" class="class">朴泰相</a>说：<span title="楼上很霸气。。。">楼上很霸气。。。...</span><br />
<span class="class">老老马</span>对<a href="/cbo_star/star_461.html" target="_blank" class="class">李雪芮</a>说：<span title="恭喜李雪芮赢得中国陵水大师赛女子单打冠军。
李雪芮打球的手法和球路真的非常厉害，如果不是腿伤令期移动不够快的话，真是打谁都不用怕的，若能将体重减轻点就好了，跑起来更轻松些，移动更快就更能打出更多好球出来，加油，雪芮妹子，再减点肥。
">恭喜李雪芮赢得中国陵水大师赛...</span><br />
<span class="class">老老马</span>对<a href="/cbo_star/star_461.html" target="_blank" class="class">李雪芮</a>说：<span title="李雪芮，加油！">李雪芮，加油！...</span><br />
</div>
</div>
<div class="right-box">
<div class="title-3"><span><a href="/cbo_user/user.php?in=shop&amp;action=add" target="_blank">登记</a></span><a href="/cbo_shop/index.php" target="_blank">最新商店信息</a></div>
<div class="list-1-1">
<a href="/cbo_shop/shop_1770.html" target="_blank">羽王传奇</a><br />
<a href="/cbo_shop/shop_1767.html" target="_blank">优个运动体育用品店</a><br />
<a href="/cbo_shop/shop_1763.html" target="_blank">以法莲体育</a><br />
<a href="/cbo_shop/shop_1762.html" target="_blank">德洛萨体育</a><br />
<a href="/cbo_shop/shop_1760.html" target="_blank">胜利专卖店 VICTOR 广</a><br />
<a href="/cbo_shop/shop_1759.html" target="_blank">瑞安体育</a><br />
<a href="/cbo_shop/shop_1757.html" target="_blank">沈阳市滔搏运动城1楼器材</a><br />
<a href="/cbo_shop/shop_1756.html" target="_blank">羽球飞舞</a><br />
<a href="/cbo_shop/shop_1755.html" target="_blank">北京东鹏康丽体育休闲设备有限公</a><br />
<a href="/cbo_shop/shop_1753.html" target="_blank">壹地羽毛体育培训</a><br />
<a href="/cbo_shop/shop_1751.html" target="_blank">LLSPORT 全自动羽毛球发</a><br />
<a href="/cbo_shop/shop_1750.html" target="_blank">合肥得乐体育用品厂</a><br />
<a href="/cbo_shop/shop_1749.html" target="_blank">卓恒体育</a><br />
<a href="/cbo_shop/shop_1748.html" target="_blank">翼之力羽毛球市体育馆店</a><br />
<a href="/cbo_shop/shop_1746.html" target="_blank">贵州肖盛球拍修复工作室</a><br />
</div>
</div>
<div class="spacer"></div>
</div>
<div class="title-1"><span><a href="/about/partner.html" target="_blank">查看更多</a></span>中羽在线合作伙伴</div><div class="box" style="border-top:1px solid #ccc; padding-top:8px;">
<table width="100%" border="0" cellspacing="2" cellpadding="0">
<tr align="center">
<td width="16%"><img src="/cbo_eq/brandLogo/lining.jpg" alt="李宁Lining" /></td>
<td width="16%"><img src="/cbo_eq/brandLogo/kason.jpg" alt="凯胜KASON" /></td>
<td width="16%"><img src="/cbo_eq/brandLogo/yonex.jpg" alt="尤尼克斯YONEX" /></td>
<td width="16%"><img src="/cbo_news/style/img/sina.jpg" alt="新浪新闻sina" /></td>
<td width="16%"><img src="/cbo_eq/brandLogo/taan.jpg" alt="泰昂TAAN" /></td>
<td width="16%"><img src="/cbo_eq/brandLogo/oliver.jpg" alt="奥立弗OLIVER" /></td>
</tr>
</table>
</div><script language='javascript' type="text/javascript" src='index.php?updata=1'></script>
<div class="footer"><a href="/about/index.html" target="_blank">关于我们</a> | <a href="about/partner.html" target="_blank">合作伙伴</a> | <a href="http://www.badmintoncn.com/link.php">友情连接</a> | <a href="about/clarify.html" target="_blank">版权声明</a> | <a href="http://t.sina.com.cn/badmintoncn" target="_blank">中羽微博</a> | <a href="/about/contact.html" target="_blank">联系我们</a><br />
Copyright &copy; badmintoncn.com 中羽在线 版权所有 闽ICP备05000173号 <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=35020302000857" style="color:#999999"><img src="/cbo_news/style/img/beian.png" align="absmiddle" />闽公网安备35020302000857号</a><br />
中羽在线合作/建议/信箱：market(a)badmintoncn.com
</div>
<style>
#bottomad_big {
WIDTH: 100%;
background: rgba(0,0,0,.75); 
text-align:center;
display:block;
overflow:hidden;
z-index:2000;
margin:0 auto;
FLOAT: right; 
RIGHT: 0px; 
BOTTOM: 0px;
POSITION:fixed;/*固定定位*/
_POSITION: absolute;/*兼容IE6*/
_TOP: expression(offsetParent.scrollTop+document.documentElement.clientHeight-this.offsetHeight);/*兼容IE6*/
}

.bottom_ad_body{width:870px;margin:0 auto;text-align:center;}
.bottom_ad_close{float:right }
</style>
<div id="bottomad_big" style="display:none;">
<span onClick="toggle()" class="bottom_ad_close"><img src="http://bbs.badmintoncn.com/cbo/close2.png" id="close_img" alt="关闭" width="40"></span>
<div id="cboas_90" class="bottom_ad_body"><cboa id="cboa_90"></div>
</div>
<script type="text/javascript">
var bottomad_big = document.getElementById('bottomad_big').style;
var week = new Date().getDay();  
//if(week == 0 || week == 5 || week == 6){ 

//if(!navigator.userAgent.match(/(iPhone|iPod|Android|ios)/i)){
log_bbsa();
//}
//}

function toggle() {
if ( bottomad_big.display == "none" ){
setCookieAd("bbsbottomcookie","yes","h0") ;
bottomad_big.display = "block"; 
}else{
setCookieAd("bbsbottomcookie","yes","h24") ;
bottomad_big.display = "none";
}
}

function log_bbsa(){

if (getCookieAd('bbsbottomcookie')=='yes'){   
bottomad_big.display = "none";
}else{
bottomad_big.display = "block";	
}


}

function getCookieAd(name){
var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");
if(arr=document.cookie.match(reg)) return unescape(arr[2]);
else return null;
}

function setCookieAd(name,value,time){
var strsec = getsecad(time);
var exp = new Date();
exp.setTime(exp.getTime() + strsec*1);
document.cookie = name + "="+ escape (value) + ";expires=" + exp.toGMTString();
}

function getsecad(str){
var str1=str.substring(1,str.length)*1; 
var str2=str.substring(0,1); 
if (str2=="s"){
return str1*1000;
}else if (str2=="h"){
return str1*60*60*1000;
}else if (str2=="d"){
return str1*24*60*60*1000;
}
}
</script>
<div style="DISPLAY: none">
<script language=javascript src="/cbo_include/cbo_top.php?action=userLogin"></script>
<script src="/cbo_include/js/cboaaa.js" type="text/javascript">
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?cfc948fc40dd345b6e12298c5c40ba13";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</div>
</div>
</div>
<script type="text/javascript" id='speedup_test' src="https://idm-su.baidu.com/su.js"></script>
</body>
</html>